# config file version
apiVersion: 1

# list of datasources to insert/update depending on what's available
datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    orgId: 1
    url: http://prometheus:9090   # service name inside Docker compose network
    basicAuth: false
    isDefault: true
    version: 1
    editable: true
    jsonData:
      timeInterval: "15s"
      httpMethod: "POST"